name: daragrennie
favicon: null
layout_spectrum: 0.1424256085883826
typography_spectrum: 0.1851683845743537
title: "Simplifying Life's Lessons"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a453e'
    - '#c3dfed'
    - '#3a7964'
    - '#84bea8'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
